name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '21.x'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
